### ISSUE TITLE
n개 이상의 키를 동시에 눌렀을 때 소리 인식 불가 

### ISSUE THREAD

**Issue by ojin0611** [ojin0611/ssapiano#12]
키보드 구조상 문제일까요?
z+c+b
v+b+n
이런 조합으로 눌렀을 때 3번째 키부터 소리가 안납니다.

**Comment by Helia-17** [comment]
이 상황에서 문제가 되는 건 키를 연속으로 눌렀을 때, 이전 오디오가 끝나지 않으면 새로운 오디오가 재생되지 않는 다는 점이다. 이를 해결하기 위해 audio의 property인 currentTime을 0으로 만들어줘 내가 틀고자하는 오디오가 이미 재생되고 있다면 처음부터 재생하게 만들어준다.

출처: https://geonlee.tistory.com/48 [빠리의 택시 운전사]

오디오로 만든 피아노 중에서 이런 내용이 있긴 한데 주파수로 한 경우에는 이럴 가능성은 없을까요?

**Comment by ojin0611** [comment]
성재님 "컴퓨터"키보드로는 되는것보니까, 제 노트북의 hardware 문제인것같아요.

**Comment by ojin0611** [comment]
hardware issue
